
development:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: nomy
  password:
  timeout: 5000
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-3-223-242-224.compute-1.amazonaws.com
  database: djs9k5gp3c3g9
  pool: 5
  username: abmuuhncreuixg
  password: 1a8c41e6c9b9100d211f7b35f4fb22f214cbb46a05465b37bfe80d96ce041972
  timeout: 5000
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: nomy
  password: jarvisai
  timeout: 5000
  port: 5432


